### ISSUE TITLE
[12pts] Finalize Project - Polishing and Deployment (Group)

### ISSUE THREAD

**Issue by IndieCoderMM** [IndieCoderMM/e-learning-academy#43]
This issue is for refactoring, bug fixes, UI improvements, and deployment tasks.

## Tasks 🎯
- [ ] Make necessary changes to UI
- [ ] Refactor code and fix bugs
- [ ] Setup deployment configurations and scripts
- [ ] Deploy the project to `Render`
- [ ] Check deployed project for any issues or errors

## Checklist ✅
- [ ] All page contents display correctly
- [ ] All pages are responsive
- [ ] All forms are working properly
- [ ] All tests are passing
